name: release
on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v*.*.*"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        module: [module_1, module_2]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all commits
          fetch-depth: 0

      - name: Semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          branch: dev
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: 'feat(\\(.+\\))?:'
          namespace: ${{ matrix.module }}
          version_format: "v${major}.${minor}.${patch}-${{ matrix.module }}"
          change_path: ${{ matrix.module }}
          debug: true
