name: release
on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v*.*.*"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all commits
          fetch-depth: 0

      - name: Semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          branch: dev
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: 'feat(\\(.+\\))?:'
          namespace: module_1
          version_format: "v${major}.${minor}.${patch}-module_1"
          change_path: "module_1"

      - name: Cancel if Unchanged
        if: ${{ ! steps.versioning.outputs.changed }}
        run: |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: ${{ steps.versioning.outputs.version }}
          prerelease: false
